### ISSUE TITLE
Embed Webview in Android Fragment no longer works in cordova 4.0

### ISSUE THREAD

**Issue by twilly86** [Adobe-Marketing-Cloud-Apps/app-sample-android-phonegap#1]
Embed Webview in Android Fragment sample code no longer works for android 4.0.

See error details here...

http://stackoverflow.com/questions/30489176/cordova-webview-inside-android-fragment-on-cordova-4-0

**Comment by arumsey** [comment]
Thanks for bringing up the issue @twilly86.  I will look into updating this sample to support Cordova 4.0.

**Comment by teamnorge** [comment]
In case you need a bigger stack trace:
android.view.InflateException: Binary XML file line #14: Class is not a View 

org.apache.cordova.CordovaWebView
            at android.view.LayoutInflater.createView(LayoutInflater.java:604)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at info.geometrixx.webview.HomeFragment.onCreateView(HomeFragment.java:63)
            ...

Caused by: java.lang.ClassCastException: org.apache.cordova.CordovaWebView cannot be cast to android.view.View
            at java.lang.Class.asSubclass(Class.java:1380)
            at android.view.LayoutInflater.createView(LayoutInflater.java:552)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at info.geometrixx.webview.HomeFragment.onCreateView(HomeFragment.java:63)

**Comment by 0x524A4B** [comment]
Is this project still being supported?

**Comment by arumsey** [comment]
Hi @runjumpkick  - Yes it is. The Android code however needs a major re-write in order to support the latest Cordova libs.

**Comment by 0x524A4B** [comment]
OK. Is there a ETA on publishing a modernized sample app?

**Comment by wayneforrest** [comment]
I am also experiencing the same problem, when can we expect an update?

**Comment by twilly86** [comment]
Check out this post, it should get you pointed in the right direction.

http://stackoverflow.com/questions/30489176/cordova-webview-inside-android-fragment-on-cordova-4-0

**Comment by wayneforrest** [comment]
Thanks;  I tweaked the code you mentioned above and got the Cordova webView showing.

Can you perhaps share your CordovaContext.java file?

```
  @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {


        //???what is CordovaContext ???
        //LayoutInflater localInflater = inflater.cloneInContext(new CordovaContext(getActivity(), this));

        //my hack
        View v = inflater.inflate(R.layout.webview_cordova, container, false);
```

**Comment by galacticappster04** [comment]
I am so tired with this JavaScript/HTML5/CSS being forced into a native app. Maybe we should stop forcing ourselves writing codes that are meant only for browsers. Just fixing this things alone isn't cost and time effective. I am moving away from this web apps thingy from now on.

**Comment by bpetriv** [comment]
@twilly86 I am working on Apache Cordova team at Microsoft. Our team is interested in understanding your experiences with embedded Cordova web views. Would you be able to fill in this quick contact info survey http://www.instant.ly/s/WGx9L so that we can get in touch with you?

**Comment by arumsey** [comment]
I finally freed up some time in my schedule to update this app. Thanks for the help @twilly86.
